version: "3.7"

networks:
  farmer-app:
    driver: bridge

services:
  sfarmer:
    image: '11082013/farmer:v0.1.2'
    container_name: sfarmer
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=farmer
      - DB_USER=root
      - DB_PASSWORD=123456
      - BINANCE_APIKEY=dg16fBBCcLsvevrj2PRoWPZDOxWXWfUswACLWgb71Hr3EWceOY6tszrnrYwkjRlc
      - BINANCE_SECRETKEY=g7pD2fazEGkm4rKHbxPIn83TniAyumLfuGyz9SPW4bjP3qEVTaS0OxEnUwVYuAwn
      - TELEBOT_TOKEN=5391392501:AAF66073DXJ1hyrsjnxFW5Q0zgN8lGKOJqE
    volumes:
      - ./volumes/log:/app/log
    networks:
      - farmer-app
    ports: 
      - "8080:8080"
    command: >
      sh -c "./server migration --up 0 && ./server sfarmer --test=${SFARMER_TEST} &> /app/log/sfarmer_log.txt"