version: "3.7"

networks:
  farmer-app:
    driver: bridge

services:
  sfarmer:
    build: ..
    container_name: sfarmer
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - BINANCE_APIKEY=${BINANCE_APIKEY}
      - BINANCE_SECRETKEY=${BINANCE_SECRETKEY}
    networks:
      - farmer-app
    command: >
      sh -c "./server migration --up 0 && ./server sfarmer --test=${SFARMER_TEST}"
