version: "3.7"

networks:
  farmer-app:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:latest'
    container_name: mysql
    volumes:
      - ./volumes/bitnami_mysql/data:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=farmer
    networks:
      - farmer-app
    ports:
      - "3406:3306"
