server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: 

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: sfarmer
          __path__: /tmp/log/sfarmer.log
